### PR TITLE
updating 1822direkt parser 

### LINKED ISSUE #3445: [1822direkt Depot] Dividendengutschrift kann nicht importiert werden
## Document
<details><summary>8007796181-ER01-54321939820-20210212.pdf</summary><p>

```json
[
  [
    "Seite 1",
    "Postfach · 60255 Frankfurt am Main",
    "Herrn",
    "Xxxxxxx Xxxßxxxxxx",
    "Xxxxxxxxxxx. 0",
    "00000 Xxxxx",
    "Xxxxxxxxxxx",
    "0000000000",
    "Xxxxxxxxxxxx",
    "0000000",
    "Xxxxxxx Xxxßxxxxxx",
    "Abrechnungsnr.",
    "00000000000",
    "Datum",
    "12.02.2021",
    "Ihr Berater",
    "1822direkt",
    "Telefon",
    "069 94170-0",
    "2158.02130100.0003595ER01",
    "Bitte ggf. Rückseite beachten.",
    "Dividendengutschrift",
    "Nominale",
    "Wertpapierbezeichnung",
    "ISIN",
    "(WKN)",
    "Stück 200",
    "APPLE INC.",
    "REGISTERED SHARES O.N.",
    "US0378331005",
    "(865985)",
    "Zahlbarkeitstag",
    "11.02.2021",
    "Bestandsstichtag",
    "04.02.2021",
    "Ex-Tag",
    "05.02.2021",
    "Geschäftsjahr",
    "01.10.2020 - 30.09.2021",
    "Devisenkurs",
    "EUR / USD",
    "1,2124",
    "Devisenkursdatum",
    "12.02.2021",
    "Dividende pro Stück",
    "0,205",
    "USD",
    "Herkunftsland",
    "USA",
    "Art der Dividende",
    "Quartalsdividende",
    "Dividendengutschrift",
    "41,00",
    "USD",
    "33,82+",
    "EUR",
    "Umrechnung in EUR",
    "33,82",
    "EUR",
    "Einbehaltene Quellensteuer 15 % auf 41,00 USD",
    "5,07-",
    "EUR",
    "Anrechenbare Quellensteuer 15 % auf 33,82 EUR",
    "5,07",
    "EUR",
    "Kapitalertragsteuerpflichtige Dividende",
    "33,82",
    "EUR",
    "Verrechneter Sparer-Pauschbetrag",
    "33,82",
    "- EUR",
    "Berechnungsgrundlage für die Kapitalertragsteuer",
    "0,00",
    "EUR",
    "Ausmachender Betrag",
    "28,75+",
    "EUR",
    "Xxxxxxxxxxx Xxxxxxxxxxx Xxxxxxx XXX (000000 / 00000000)",
    "Den Betrag buchen wir mit Wertstellung 15.02.2021 zu Gunsten des Kontos 1244416540 (IBAN XX00 0000 0000 0000",
    "0000 00), XXX 000 000 00 (XXX XXXXXXX0000).",
    "Keine Steuerbescheinigung."
  ],
  [],
  [
    "Seite 2",
    "Xxxxxxxxxxx",
    "0000000000",
    "Xxxxxxxxxxxx",
    "0000000",
    "Abrechnungsnr.",
    "00000000000",
    "Datum",
    "12.02.2021",
    "2158.02130100.0003596ER01",
    "Dieses Dokument wurde maschinell erstellt und wird nicht unterschrieben.",
    "Nachrichtlich die Übersicht Ihrer Verrechnungs- und Steuertopfsalden zum Zeitpunkt der Erstellung der Abrechnung.",
    "Verrechnungstöpfe 2021",
    "Berechnungsgrundlage",
    "der gezahlten Steuern",
    "Euro",
    "Aktien",
    "Sonstige",
    "Sparer-",
    "Pauschbetrag",
    "anrechenbare",
    "Quellensteuer",
    "Aktien und Sonstige",
    "Vorher",
    "49,56",
    "0,00",
    "801,00",
    "0,00",
    "0,00",
    "Ertrag",
    "0,00",
    "0,00",
    "33,82-",
    "5,07",
    "0,00",
    "Nachher",
    "49,56",
    "0,00",
    "767,18",
    "5,07",
    "0,00"
  ]
]

```

</p></details>

## Community profile

https://community.parqet.com/u/ea350589

---
Issue submitted with https://import.parqet.com

### PR DESCRIPTION
**Pull request by phaus**
Did update the parser for 1822direkt "Dividendengutschrift", works locally, should fix my own issue (#3445).

### CODE REVIEW

**Comment by dredav** [comment]
Thanks for you PR! Can you please add a test case which contains the document form #3445?

**Comment by phaus** [comment]
Hi  @dredav !

I just added a test case for the original document.

**Review by dredav — DISMISSED** [review]
- Fix #3445

Look good. Thanks for contributing!

**Comment by dredav** [comment]
Just wating for the CI check to report a status 🤔 ...

**Comment by dredav** [comment]
Looks like a GH issue right now...

Screenshot 2021-08-10 at 22 57 01

**Comment by dredav** [comment]
Can you push a small change to trigger the github action again? Can't find a way to do this inside this PR...

**Review by dredav — APPROVED** [review]

**Pull request merged**
