### PR TITLE
add italian string conditions (Degiro import)

### PR DESCRIPTION
**Pull request by Zemmor**

### CODE REVIEW

**Comment by dredav** [comment]
@Zemmor Thanks for you PR. Can you add a test case with an italien degiro file? You can anonymize your document with https://import.tresor.one and the use the issue content as a new test case. This will help to make the implementation with the italian content resilient in the future.

**Comment by Zemmor** [comment]
I don`t know why my test fail. Their is somewhere a datetime Problem

**Comment by Heisenbyte** [comment]
if you commit your tests i can help :))

**Comment by Zemmor** [comment]
Ok the Test passed. 
@dredav  Their is some error in the parsedate function. If you run the test befor 12 pm it works fine -> if you run the test after 12 pm fails. I think it is because of "UTC" is one hour back and then you receive the wrong date.

Example: https://github.com/tresorone/tresor-import/runs/2162066403

**Review by dredav — APPROVED** [review]

**Comment by dredav** [comment]
Thanks for adding the tests @Zemmor. Yes there is an issue with out tests - we need on the long side a small test refactoring that prevents the 12pm issue.

**Pull request merged**
