### PR TITLE
[WIP] Add support for InteractiveBrokers

### PR DESCRIPTION
**Pull request by Double-A-92**
Hello

I'm trying to add support for InteractiveBrokers reports. 
I **almost** got it to work for German ActivityStatements in CSV format (the PDF is too tedious to parse).

However I have a problem with the currency exchange rate. At InteractiveBrokers you have to manually convert your currencies before you buy assets, so a trade doesn't have an individual rate associated to it.

Is there a way to work around that? Maybe a service that gets the exchange rate to EUR at a specific date time? That could at least approximate the costs in EUR.

### CODE REVIEW

**Comment by dredav** [comment]
Thanks for you PR and sorry for my late response.

> At InteractiveBrokers you have to manually convert your currencies before you buy assets, so a trade doesn't have an individual rate associated to it.

So in which currency is the trade written in the csv file? I guess not in EUR? Currently we don't support activities without an fx rate **but** may I can discuss a possible solution for this with the team (where T1 Core do the currency conversion from *** to EUR.

**Comment by Double-A-92** [comment]
The trade will  be written in the trading currency as it was on the exchange (no matter what the base currency of the account is). 
The field activity.foreignCurrency is always filled with that information.

I have seen that T1 offers a historic currency API, so maybe that could be used to fill the missing information.

**Comment by dredav** [comment]
Minor update for the currency topic: We will soon implement the handling of activities for non euro currencies. I will provide the activity structure for this after they was finally approved.

**Comment by MichaelSp** [comment]
@dredav  any update on the currency handling?

**Pull request closed without merging**
